apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stockie-backend
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/min-instances: "0"
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/stockie-backend:v1.0.0
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: production
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: latest
#              value: YOUR_DB_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: latest
#              value: redis://redis:6379
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
      timeoutSeconds: 300
  traffic:
    - percent: 100
      latestRevision: true