#simulate prod locally
#version: "3.9"

services:
  backend:
    container_name: stockie-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: stockie-redis
    ports:
      - "6379:6379"
    restart: unless-stopped