[tool.black]
line-length = 88
target-version = ['py312']
include = '/(app|tests)/.*\.py$'
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["sqlalchemy"]
src_paths = ["app", "tests"]