region        = "asia-southeast1"
# debug         = "false"
# log_level     = "INFO"
# allowed_origins = "https://stockie-fe.vercel.app/,http://localhost:5173,http://localhost:8000,http://localhost:8001"
backend_domain = "stockie-service-996128501833.asia-southeast1.run.app"
scheduler_service_account = "stockie-deploy-sa@crafty-tracker-398607.iam.gserviceaccount.com"
backend_api_key = "stockie-backend-secret-key"
project_id = "crafty-tracker-398607"