"""Initial schema

Revision ID: 210f28d91c0d
Revises:
Create Date: 2025-03-30 01:17:11.928045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "210f28d91c0d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "industries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_industries_code"), "industries", ["code"], unique=True)
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("industry_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industries.id"], name="fk_stocks_industry_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stocks_industry_id"), "stocks", ["industry_id"], unique=False
    )
    op.create_index(op.f("ix_stocks_ticker"), "stocks", ["ticker"], unique=True)
    op.create_table(
        "top_predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column(
            "calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industries.id"], name="fk_top_predictions_industry_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_top_predictions_industry_target_period",
        "top_predictions",
        ["industry_id", "target_date", "period"],
        unique=False,
    )
    op.create_table(
        "stock_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("version_tag", sa.String(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("saved_path", sa.String(), nullable=True),
        sa.Column("model_type", sa.String(), nullable=True),
        sa.Column("model_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
            name="fk_stock_models_stock_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_models_stock_id"), "stock_models", ["stock_id"], unique=False
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column(
            "predicted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("predicted_price", sa.Float(), nullable=False),
        sa.Column("actual_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["stock_models.id"],
            name="fk_predictions_model_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
            name="fk_predictions_stock_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_predictions_industry_target_period",
        "predictions",
        ["stock_id", "target_date", "period"],
        unique=False,
    )
    op.create_table(
        "top_prediction_ranks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("top_prediction_id", sa.Integer(), nullable=False),
        sa.Column("prediction_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"], ["predictions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["top_prediction_id"], ["top_predictions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_top_prediction_ranks_top_prediction_id",
        "top_prediction_ranks",
        ["top_prediction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_top_prediction_ranks_top_prediction_id", table_name="top_prediction_ranks"
    )
    op.drop_table("top_prediction_ranks")
    op.drop_index("ix_predictions_industry_target_period", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index(op.f("ix_stock_models_stock_id"), table_name="stock_models")
    op.drop_table("stock_models")
    op.drop_index(
        "ix_top_predictions_industry_target_period", table_name="top_predictions"
    )
    op.drop_table("top_predictions")
    op.drop_index(op.f("ix_stocks_ticker"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_industry_id"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_index(op.f("ix_industries_code"), table_name="industries")
    op.drop_table("industries")
    # ### end Alembic commands ###
