"""Industry column name change

Revision ID: 9b4ec4b77248
Revises: d7a94e625826
Create Date: 2025-04-06 19:25:55.565716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4ec4b77248'
down_revision: Union[str, None] = 'd7a94e625826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industries', sa.Column('name_en', sa.String(length=100), nullable=False))
    op.add_column('industries', sa.Column('name_th', sa.String(length=100), nullable=False))
    op.add_column('industries', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('industries', sa.Column('description_th', sa.Text(), nullable=True))
    op.drop_column('industries', 'descriptionEN')
    op.drop_column('industries', 'nameEN')
    op.drop_column('industries', 'nameTH')
    op.drop_column('industries', 'descriptionTH')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industries', sa.Column('descriptionTH', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('industries', sa.Column('nameTH', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('industries', sa.Column('nameEN', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('industries', sa.Column('descriptionEN', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('industries', 'description_th')
    op.drop_column('industries', 'description_en')
    op.drop_column('industries', 'name_th')
    op.drop_column('industries', 'name_en')
    # ### end Alembic commands ###
