from enum import Enum


class JobStatusEnum(str, Enum):
    STARTED = "🚀 Job started"
    SUCCESS = "✅ Job completed"
    FAILED = "❌ Job failed"
    SKIPPED = "⚠️ Job skipped"
    WARNING = "⚠️ Job warning"


class JobTypeEnum(str, Enum):
    INFERENCE = "Run Inference"
    RANK = "Rank Predictions"
    EVALUATION = "Evaluate Accuracy"
    CLEANUP = "Cleanup Old Data"
    PULL_FEATURES = "Pull Features"


class JobConfigEnum(str, Enum):
    PULL_FEATURES_CIRCUIT_BREAKER = "PULL_FEATURES_CIRCUIT_BREAKER"

    # inference variables
    RUN_INFERENCE_CIRCUIT_BREAKER = "RUN_INFERENCE_CIRCUIT_BREAKER"
    RUN_INFERENCE_DAYS_BACK = "RUN_INFERENCE_DAYS_BACK"
    RUN_INFERENCE_DAYS_FORWARD = "RUN_INFERENCE_DAYS_FORWARD"
    SAVE_INFERENCE_PERIODS = "SAVE_INFERENCE_PERIODS"

    # evaluation variables
    EVALUATE_CIRCUIT_BREAKER = "EVALUATE_CIRCUIT_BREAKER"
    EVALUATE_DAYS_BACK = "EVALUATE_DAYS_BACK"

    # cleanup variables
    CLEANUP_CIRCUIT_BREAKER = "CLEANUP_CIRCUIT_BREAKER"
    CLEANUP_FEATURES_DAYS_BACK = "CLEANUP_FEATURES_DAYS_BACK"
    CLEANUP_PREDICTIONS_DAYS_BACK = "CLEANUP_PREDICTIONS_DAYS_BACK"

    LAST_SUCCESS_INFERENCE = "LAST_SUCCESS_INFERENCE"
    LAST_SUCCESS_EVALUATION = "LAST_SUCCESS_EVALUATION"
    LAST_SUCCESS_RANK = "LAST_SUCCESS_RANK"
    LAST_SUCCESS_CLEANUP = "LAST_SUCCESS_CLEANUP"
    LAST_SUCCESS_PULL_FEATURES = "LAST_SUCCESS_PULL_FEATURES"
